.TL
My first groff document
.AU
Julio Cabanillas
.AI
Private University of North
.AB
This is an abstract
.AE
.NH
Introduction
.PP
This is a paragraph. 
Asdflkjsdfsdlfkjsdlfjsadfjlsjdflkjsldfjalsdfj
Asdflkjsdfsdlfkjsdlfjsadfjlsjdflkjsldfjalsdfj
Asdflkjsdfsdlfkjsdlfjsadfjlsjdflkjsldfjalsdfj
Asdflkjsdfsdlfkjsdlfjsadfjlsjdflkjsldfjalsdfj


Another sentence.
.PP
Add a sentences
.NH
Second Section
.NH 2
SubSection
.NH 2
Another SubSection

.PP
Here is some more text. I want the word 
.B "bold"
to be bold.
We can have
.I "italic text"
with .I
